get new mock above, do not tidy or run
if you don't do this first, this happens because the generated code breaks the ability to generate new code:
```
running go generate ./..., this takes a minute or more...
27 Dec 24 16:44 CST INF couldn't read any config file version=v2.32.0
2024/12/27 16:45:11 Loading input failed: load package: /Users/stevenl/go/src/github.com/uber/cadence/common/persistence/data_manager_interfaces_mock.go:17:9: could not import go.uber.org/mock/gomock (invalid package name: "")
common/persistence/data_store_interfaces.go:35: running "mockgen": exit status 1
2024/12/27 16:45:15 Loading input failed: load package: /Users/stevenl/go/src/github.com/uber/cadence/common/quotas/limiterfactory_mock.go:20:19: undefined: gomock.Controller
/Users/stevenl/go/src/github.com/uber/cadence/common/quotas/limiterfactory_mock.go:31:41: undefined: gomock.Controller
/Users/stevenl/go/src/github.com/uber/cadence/common/quotas/limiterfactory_mock.go:51:74: undefined: gomock.Call
common/quotas/interfaces.go:21: running "mockgen": exit status 1
make: *** [go-generate] Interrupt: 2
```